tasks:
  - name: Setup Conda Environment
    init: |
      export PATH=$PATH:/home/gitpod/.pyenv/versions/3.12.6/bin
      export PATH=$PATH:~/mirtop_env/bin
      echo "export PATH=\$PATH:~/mirtop_env/bin" >> ~/.bashrc
      echo "export PATH=\$PATH:/home/gitpod/.pyenv/versions/3.12.6/bin" >> ~/.bashrc
      wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O ~/miniconda.sh
      bash ~/miniconda.sh -b -p ~/mirtop_env
      conda config --set ssl_verify false  # For Gitpod compatibility
      conda install anaconda-client -y
      conda install -c bioconda samtools
      pip install pytest pyyaml six pysam pybedtools pandas biopython
